import type { FunnelIcon } from "./funnel";
import {
  BoilerIcon,
  ServiceIcon,
  NewBoilerIcon,
  PlumbingIcon,
  ElectricsIcon,
  LandlordIcon,
  BuildingIcon,
  QuestionIcon,
  TapIcon,
  BathIcon,
  RadiatorIcon,
  LeakIcon,
  FuseboxIcon,
  PlugIcon,
  BulbIcon,
  EvIcon,
  OvenIcon,
  NoteIcon,
  CalendarIcon,
  AlertTriangleIcon,
} from "@/components/icons";

// Maps the funnel's icon keys to components, so funnel.ts stays plain data.
export const funnelIconMap: Record<FunnelIcon, typeof BoilerIcon> = {
  boiler: BoilerIcon,
  service: ServiceIcon,
  newboiler: NewBoilerIcon,
  plumbing: PlumbingIcon,
  electrics: ElectricsIcon,
  landlord: LandlordIcon,
  building: BuildingIcon,
  question: QuestionIcon,
  tap: TapIcon,
  bath: BathIcon,
  radiator: RadiatorIcon,
  leak: LeakIcon,
  fusebox: FuseboxIcon,
  plug: PlugIcon,
  bulb: BulbIcon,
  ev: EvIcon,
  oven: OvenIcon,
  clipboard: NoteIcon,
  calendar: CalendarIcon,
  alert: AlertTriangleIcon,
};
